/*
 * WordCipherGameApp.java
 *
 * Copyright (c) 2010 Rob Just
 */

package edu.baker.cs.cs242.finalProject.WordCipherGame;

import org.jdesktop.application.Application;
import org.jdesktop.application.SingleFrameApplication;

/**
 * Class: WordCipherGameApp
 * Description: Class that creates the Main window. Generated by NetBeans.
 * Modified by Rob Just to set title, size, and resizable to false.
 *
 *
 * @author     Rob Just
 * @created    September 15th, 2010
 */
public class WordCipherGameApp extends SingleFrameApplication {

    /**
     * At startup create and show the main frame of the application.
     */
    @Override protected void startup() {
        show(new WordCipherGameView(this));
        getMainFrame().setTitle("Word Cipher Game"); // Set Title
        getMainFrame().setSize(555, 400); // Set size of window
        getMainFrame().setResizable(false); // Do not allow resizing
    }

    /**
     * This method is to initialize the specified window by injecting resources.
     * Windows shown in our application come fully initialized from the GUI
     * builder, so this additional configuration is not needed.
     */
    @Override protected void configureWindow(java.awt.Window root) {
    }

    /**
     * A convenient static getter for the application instance.
     * @return the instance of WordCipherGameApp
     */
    public static WordCipherGameApp getApplication() {
        return Application.getInstance(WordCipherGameApp.class);
    }

    /**
     * Main method launching the application.
     */
    public static void main(String[] args) {
        launch(WordCipherGameApp.class, args);
    }
}
