/*
 * WordCipherGameView.java
 *
 * Copyright (c) 2010 Rob Just
 */

package edu.baker.cs.cs242.finalProject.WordCipherGame;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.util.NoSuchElementException;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Class: WordCipherGameView
 * Description: Class that initializes the window, controls, and event handlers.
 * Contains main program code to play the Word cipher game using a CipherGame
 * object.
 *
 *
 * @author     Rob Just
 * @created    September 15th, 2010
 */
public class WordCipherGameView extends FrameView {

    
    private JDialog aboutBox; // About Box dialog
    private CipherGame cipherGame; // CipherGame object that manages the game

    // Constructor the initializes components and starts the game
    public WordCipherGameView(SingleFrameApplication app) {
        super(app);
        initComponents();
        startNewGame();
    }

    // Show About Box window
    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = WordCipherGameApp.getApplication().getMainFrame();
            aboutBox = new WordCipherGameAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        WordCipherGameApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tfPlayersGuess = new javax.swing.JTextField();
        btnGuess = new javax.swing.JButton();
        btnHint = new javax.swing.JButton();
        lblPlayersGuess = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblAttempts = new javax.swing.JLabel();
        lblHint = new javax.swing.JLabel();
        lblCurrentWord = new javax.swing.JLabel();
        lblLastWord = new javax.swing.JLabel();
        lblWordsRemaining = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfPlayersGuess.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfPlayersGuess.setName("tfPlayersGuess"); // NOI18N
        tfPlayersGuess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPlayersGuessKeyPressed(evt);
            }
        });
        mainPanel.add(tfPlayersGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 180, 30));

        btnGuess.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuess.setText("Guess!");
        btnGuess.setToolTipText("Submits your guess.");
        btnGuess.setName("btnGuess"); // NOI18N
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });
        mainPanel.add(btnGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 90, 30));

        btnHint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHint.setText("Hint!");
        btnHint.setToolTipText("<html>Hints cost you 1 attempt.<br>You can have a maximum of 4 hints.<br>Hints do not reveal the last letter of a word."); // NOI18N
        btnHint.setName("btnHint"); // NOI18N
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });
        mainPanel.add(btnHint, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 90, 30));

        lblPlayersGuess.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPlayersGuess.setText("Your Guess:");
        lblPlayersGuess.setName("lblPlayersGuess"); // NOI18N
        mainPanel.add(lblPlayersGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 30));

        lblSubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSubject.setText("Subject: ");
        lblSubject.setName("lblSubject"); // NOI18N
        mainPanel.add(lblSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        btnNewGame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNewGame.setText("New Game");
        btnNewGame.setToolTipText("Starts a new game.");
        btnNewGame.setName("btnNewGame"); // NOI18N
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });
        mainPanel.add(btnNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 190, 40));

        lblResult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblResult.setText("Result: ");
        lblResult.setName("lblResult"); // NOI18N
        mainPanel.add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lblScore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblScore.setForeground(java.awt.Color.blue);
        lblScore.setText("Your Score:");
        lblScore.setName("lblScore"); // NOI18N
        mainPanel.add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        lblAttempts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAttempts.setText("Attempts Remaining:");
        lblAttempts.setName("lblAttempts"); // NOI18N
        mainPanel.add(lblAttempts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        lblHint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHint.setForeground(java.awt.Color.gray);
        lblHint.setText(" ");
        lblHint.setName("lblHint"); // NOI18N
        mainPanel.add(lblHint, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 390, -1));

        lblCurrentWord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCurrentWord.setForeground(java.awt.Color.blue);
        lblCurrentWord.setText(" ");
        lblCurrentWord.setName("lblCurrentWord"); // NOI18N
        mainPanel.add(lblCurrentWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 390, -1));

        lblLastWord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLastWord.setText("Last Word: ");
        lblLastWord.setToolTipText("");
        lblLastWord.setName("lblLastWord"); // NOI18N
        mainPanel.add(lblLastWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        lblWordsRemaining.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWordsRemaining.setText("Word Remaining: ");
        lblWordsRemaining.setName("lblWordsRemaining"); // NOI18N
        mainPanel.add(lblWordsRemaining, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jSeparator1.setName("jSeparator1"); // NOI18N
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 470, 10));

        jSeparator2.setName("jSeparator2"); // NOI18N
        mainPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 470, 10));

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText("File");

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(edu.baker.cs.cs242.finalProject.WordCipherGame.WordCipherGameApp.class).getContext().getActionMap(WordCipherGameView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setText("About...");
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents
    // Event handler for Guess button
    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        submitGuess();
    }//GEN-LAST:event_btnGuessActionPerformed
    // Event handler for Hint Button
    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintActionPerformed
        getHint();
    }//GEN-LAST:event_btnHintActionPerformed
    // Event Handler for New Game Button
    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        startNewGame();
    }//GEN-LAST:event_btnNewGameActionPerformed
    // Event handler for when enter is pressed in tfPlayersGuess text field
    private void tfPlayersGuessKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPlayersGuessKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            submitGuess();
        }
    }//GEN-LAST:event_tfPlayersGuessKeyPressed
    // Method to update all the labels with relative information, calls showGameOver
    private void updateLabels()
    {
        lblScore.setText("Your Score: " 
                + Integer.toString(cipherGame.getPlayersScore()));
        lblAttempts.setText("Attempts Remaining: "
                + Integer.toString(cipherGame.getGuessAttemptsRemaining()));
        lblCurrentWord.setText(cipherGame.getCipheredWord());
        lblSubject.setText("Subject: " + cipherGame.getSubject());
        lblHint.setText(cipherGame.getHint());
        lblWordsRemaining.setText("Words Remaining: "
                + Integer.toString(cipherGame.getNumberOfWordsRemaining()));

        if (cipherGame.getGameOver())
        {
            btnGuess.setEnabled(false);
            btnHint.setEnabled(false);
            tfPlayersGuess.setEnabled(false);
            showGameOver();
        }
        else
        {
            tfPlayersGuess.setEnabled(true);
            btnGuess.setEnabled(true);
            btnHint.setEnabled(true);
        }

    }

    // Method to start a new game. Handles execeptions encountered with file.
    private void startNewGame()
    {
        try
        {
            cipherGame = new CipherGame("CipherGameWordList.txt");
            lblResult.setForeground(Color.black);
            lblResult.setText("Result: ");
            lblLastWord.setText("Last Word: ");
            updateLabels();
        }
        catch (FileNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, 
                    "Error opening file "
                    + "CipherGameWordList.txt."
                    + "\nPlease make sure the file exists "
                    + "in the current directory."
                    + "\n\nExiting program...",
                    "Error Opening File",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        catch (NoSuchElementException ex)
        {
            JOptionPane.showMessageDialog(null, 
                    "Invalid file format in "
                    + "CipherGameWordList.txt. \nFormat must be:"
                    + "\nSubject1 word1"
                    + "\nSubject2 word2"
                    + "\netc..."
                    + "\n\nExiting program...",
                    "Invalid File Format",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    // Method to start a new round. Gets new word and calls updateLabels.
    private void startNextRound()
    {
        lblLastWord.setText("Last Word: " + cipherGame.getCurrentWord());

        if (cipherGame.getGameOver())
        {
            showGameOver();
        }
        else
        {
           cipherGame.startNextRound();
           updateLabels();
        }
        
    }

    // Method to display game over message and final score to player.
    private void showGameOver()
    {
        lblSubject.setText("Game Over");
        lblCurrentWord.setText("Your Score: " + cipherGame.getPlayersScore());
        lblHint.setText("Click New Game to play again.");
        lblResult.setForeground(Color.black);
        lblResult.setText("Result: ");
    }

    // Method to submit players guess and verify if it was correct or not
    private void submitGuess()
    {
        if (cipherGame.getGameOver())
        {
            showGameOver();
        }
        else
        {
            // Player didn't type anything in
            if (tfPlayersGuess.getText().trim().isEmpty())
            {
                lblResult.setForeground(Color.red);
                lblResult.setText("Result: You didn't type in a guess!");
                tfPlayersGuess.setText("");
            }
            else
            {   // Players guess was correct
                if (cipherGame.checkPlayersGuess(tfPlayersGuess.getText()))
                {
                    lblResult.setForeground(new Color(0, 100, 0)); // Dark Green
                    lblResult.setText("Result: Your guess of "
                            + tfPlayersGuess.getText() + " was correct!");
                    tfPlayersGuess.setText("");
                    startNextRound();
                }
                else
                {   // Players guess was incorrect
                    lblResult.setForeground(Color.red);
                    lblResult.setText("Result: Your guess of "
                            + tfPlayersGuess.getText() + " was incorrect!");
                    tfPlayersGuess.setText("");

                    if (cipherGame.getGuessAttemptsRemaining() <= 0)
                    {
                        startNextRound();
                    }
                }
                updateLabels();
            }

        }
    }

    // Method to get hint from cipherGame and updates lblHint label
    private void getHint()
    {
        if (cipherGame.getGuessAttemptsRemaining() < 1)
        {
            JOptionPane.showMessageDialog(null, "You need at least 1 attempt "
                    + "remaining to get a hint.");
        }
        else
        {
            lblHint.setText(cipherGame.getNextHint());
        }
        updateLabels();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnHint;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAttempts;
    private javax.swing.JLabel lblCurrentWord;
    private javax.swing.JLabel lblHint;
    private javax.swing.JLabel lblLastWord;
    private javax.swing.JLabel lblPlayersGuess;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblWordsRemaining;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField tfPlayersGuess;
    // End of variables declaration//GEN-END:variables


}
